version: '3'

services:
  back:
    build: ./backend
    container_name: django2
    command: python manage.py runserver 0.0.0.0:8090
    ports:
      - "8090:8090"
    volumes:
      - ./backend/:/code
    env_file:
      - ./.env.dev
    depends_on:
      - database
    links:
      - database
    stdin_open: true
    tty: true

  database:
    container_name: postgres2
    image: postgres:latest
    volumes:
      - postgres_data2:/var/lib/postgresql/data2/
    env_file:
      - ./.env.dev
    ports:
      - "5433:5433"

volumes:
  postgres_data2:
